image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

docker-build:
  stage: package
  only:
    - tags
  script:
  - docker build -t registry.gitlab.com/e3opticalgroup/image-tool:$CI_COMMIT_TAG .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/e3opticalgroup/image-tool:$CI_COMMIT_TAG
